//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistribucionConEntidadesWs", Namespace="http://web.logictracker.com/")]
    public partial class DistribucionConEntidadesWs : object
    {
        
        private int EmpresaField;
        
        private ServiceReference.BaseOperativaWs BaseOperativaField;
        
        private ServiceReference.ClienteWs[] ClientesField;
        
        private ServiceReference.TransportistaWs TransportistaField;
        
        private ServiceReference.VehiculoWs VehiculoField;
        
        private ServiceReference.ChoferWs ChoferField;
        
        private string CodigoViajeField;
        
        private System.DateTime FechaTurnoField;
        
        private System.DateTime FechaInicioField;
        
        private string CodigoTipoCicloField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference.BaseOperativaWs BaseOperativa
        {
            get
            {
                return this.BaseOperativaField;
            }
            set
            {
                this.BaseOperativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference.ClienteWs[] Clientes
        {
            get
            {
                return this.ClientesField;
            }
            set
            {
                this.ClientesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference.TransportistaWs Transportista
        {
            get
            {
                return this.TransportistaField;
            }
            set
            {
                this.TransportistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServiceReference.VehiculoWs Vehiculo
        {
            get
            {
                return this.VehiculoField;
            }
            set
            {
                this.VehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ServiceReference.ChoferWs Chofer
        {
            get
            {
                return this.ChoferField;
            }
            set
            {
                this.ChoferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CodigoViaje
        {
            get
            {
                return this.CodigoViajeField;
            }
            set
            {
                this.CodigoViajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaTurno
        {
            get
            {
                return this.FechaTurnoField;
            }
            set
            {
                this.FechaTurnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CodigoTipoCiclo
        {
            get
            {
                return this.CodigoTipoCicloField;
            }
            set
            {
                this.CodigoTipoCicloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseOperativaWs", Namespace="http://web.logictracker.com/")]
    public partial class BaseOperativaWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string CoordenadasField;
        
        private string DireccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Coordenadas
        {
            get
            {
                return this.CoordenadasField;
            }
            set
            {
                this.CoordenadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportistaWs", Namespace="http://web.logictracker.com/")]
    public partial class TransportistaWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string CoordenadasField;
        
        private string DireccionField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Coordenadas
        {
            get
            {
                return this.CoordenadasField;
            }
            set
            {
                this.CoordenadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoWs", Namespace="http://web.logictracker.com/")]
    public partial class VehiculoWs : object
    {
        
        private string PatenteField;
        
        private ServiceReference.TransportistaWs TransportistaField;
        
        private ServiceReference.TipoVehiculoWs TipoVehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Patente
        {
            get
            {
                return this.PatenteField;
            }
            set
            {
                this.PatenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.TransportistaWs Transportista
        {
            get
            {
                return this.TransportistaField;
            }
            set
            {
                this.TransportistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference.TipoVehiculoWs TipoVehiculo
        {
            get
            {
                return this.TipoVehiculoField;
            }
            set
            {
                this.TipoVehiculoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChoferWs", Namespace="http://web.logictracker.com/")]
    public partial class ChoferWs : object
    {
        
        private string LegajoField;
        
        private string DescripcionField;
        
        private string TelefonoField;
        
        private ServiceReference.TransportistaWs TransportistaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Legajo
        {
            get
            {
                return this.LegajoField;
            }
            set
            {
                this.LegajoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference.TransportistaWs Transportista
        {
            get
            {
                return this.TransportistaField;
            }
            set
            {
                this.TransportistaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteWs", Namespace="http://web.logictracker.com/")]
    public partial class ClienteWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string CoordenadasField;
        
        private string DireccionField;
        
        private string TelefonoField;
        
        private ServiceReference.TipoClienteWs TipoClienteField;
        
        private System.DateTime FechaProgramadoField;
        
        private int TipoEntregaField;
        
        private ServiceReference.RemitoCompletoWs[] RemitosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Coordenadas
        {
            get
            {
                return this.CoordenadasField;
            }
            set
            {
                this.CoordenadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ServiceReference.TipoClienteWs TipoCliente
        {
            get
            {
                return this.TipoClienteField;
            }
            set
            {
                this.TipoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaProgramado
        {
            get
            {
                return this.FechaProgramadoField;
            }
            set
            {
                this.FechaProgramadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int TipoEntrega
        {
            get
            {
                return this.TipoEntregaField;
            }
            set
            {
                this.TipoEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ServiceReference.RemitoCompletoWs[] Remitos
        {
            get
            {
                return this.RemitosField;
            }
            set
            {
                this.RemitosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoClienteWs", Namespace="http://web.logictracker.com/")]
    public partial class TipoClienteWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemitoCompletoWs", Namespace="http://web.logictracker.com/")]
    public partial class RemitoCompletoWs : object
    {
        
        private string CodigoField;
        
        private ServiceReference.InsumoCompletoWs[] InsumosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.InsumoCompletoWs[] Insumos
        {
            get
            {
                return this.InsumosField;
            }
            set
            {
                this.InsumosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsumoCompletoWs", Namespace="http://web.logictracker.com/")]
    public partial class InsumoCompletoWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private int CantidadField;
        
        private double AltoField;
        
        private double AnchoField;
        
        private double LongitudField;
        
        private double PesoField;
        
        private double VolumenField;
        
        private double ValorReferenciaField;
        
        private ServiceReference.TipoInsumoWs TipoInsumoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Alto
        {
            get
            {
                return this.AltoField;
            }
            set
            {
                this.AltoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Ancho
        {
            get
            {
                return this.AnchoField;
            }
            set
            {
                this.AnchoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Longitud
        {
            get
            {
                return this.LongitudField;
            }
            set
            {
                this.LongitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Peso
        {
            get
            {
                return this.PesoField;
            }
            set
            {
                this.PesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double Volumen
        {
            get
            {
                return this.VolumenField;
            }
            set
            {
                this.VolumenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double ValorReferencia
        {
            get
            {
                return this.ValorReferenciaField;
            }
            set
            {
                this.ValorReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ServiceReference.TipoInsumoWs TipoInsumo
        {
            get
            {
                return this.TipoInsumoField;
            }
            set
            {
                this.TipoInsumoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoInsumoWs", Namespace="http://web.logictracker.com/")]
    public partial class TipoInsumoWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoVehiculoWs", Namespace="http://web.logictracker.com/")]
    public partial class TipoVehiculoWs : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResponse", Namespace="http://web.logictracker.com/")]
    public partial class GenericResponse : object
    {
        
        private int CodigoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.logictracker.com/", ConfigurationName="ServiceReference.CrearDistribucionConEntidadesSoap")]
    public interface CrearDistribucionConEntidadesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.logictracker.com/CreateDistribucionConEntidades", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CreateDistribucionConEntidadesResponse> CreateDistribucionConEntidadesAsync(ServiceReference.CreateDistribucionConEntidadesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDistribucionConEntidadesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDistribucionConEntidades", Namespace="http://web.logictracker.com/", Order=0)]
        public ServiceReference.CreateDistribucionConEntidadesRequestBody Body;
        
        public CreateDistribucionConEntidadesRequest()
        {
        }
        
        public CreateDistribucionConEntidadesRequest(ServiceReference.CreateDistribucionConEntidadesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.logictracker.com/")]
    public partial class CreateDistribucionConEntidadesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.DistribucionConEntidadesWs request;
        
        public CreateDistribucionConEntidadesRequestBody()
        {
        }
        
        public CreateDistribucionConEntidadesRequestBody(ServiceReference.DistribucionConEntidadesWs request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDistribucionConEntidadesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDistribucionConEntidadesResponse", Namespace="http://web.logictracker.com/", Order=0)]
        public ServiceReference.CreateDistribucionConEntidadesResponseBody Body;
        
        public CreateDistribucionConEntidadesResponse()
        {
        }
        
        public CreateDistribucionConEntidadesResponse(ServiceReference.CreateDistribucionConEntidadesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.logictracker.com/")]
    public partial class CreateDistribucionConEntidadesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.GenericResponse CreateDistribucionConEntidadesResult;
        
        public CreateDistribucionConEntidadesResponseBody()
        {
        }
        
        public CreateDistribucionConEntidadesResponseBody(ServiceReference.GenericResponse CreateDistribucionConEntidadesResult)
        {
            this.CreateDistribucionConEntidadesResult = CreateDistribucionConEntidadesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CrearDistribucionConEntidadesSoapChannel : ServiceReference.CrearDistribucionConEntidadesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CrearDistribucionConEntidadesSoapClient : System.ServiceModel.ClientBase<ServiceReference.CrearDistribucionConEntidadesSoap>, ServiceReference.CrearDistribucionConEntidadesSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrearDistribucionConEntidadesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CrearDistribucionConEntidadesSoapClient.GetBindingForEndpoint(endpointConfiguration), CrearDistribucionConEntidadesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearDistribucionConEntidadesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrearDistribucionConEntidadesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearDistribucionConEntidadesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrearDistribucionConEntidadesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrearDistribucionConEntidadesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CreateDistribucionConEntidadesResponse> ServiceReference.CrearDistribucionConEntidadesSoap.CreateDistribucionConEntidadesAsync(ServiceReference.CreateDistribucionConEntidadesRequest request)
        {
            return base.Channel.CreateDistribucionConEntidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CreateDistribucionConEntidadesResponse> CreateDistribucionConEntidadesAsync(ServiceReference.DistribucionConEntidadesWs request)
        {
            ServiceReference.CreateDistribucionConEntidadesRequest inValue = new ServiceReference.CreateDistribucionConEntidadesRequest();
            inValue.Body = new ServiceReference.CreateDistribucionConEntidadesRequestBody();
            inValue.Body.request = request;
            return ((ServiceReference.CrearDistribucionConEntidadesSoap)(this)).CreateDistribucionConEntidadesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearDistribucionConEntidadesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearDistribucionConEntidadesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrearDistribucionConEntidadesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://web.logictracker.com:10440/App_services/CrearDistribucionConEntidades.asm" +
                        "x");
            }
            if ((endpointConfiguration == EndpointConfiguration.CrearDistribucionConEntidadesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://web.logictracker.com:10440/App_services/CrearDistribucionConEntidades.asm" +
                        "x");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CrearDistribucionConEntidadesSoap,
            
            CrearDistribucionConEntidadesSoap12,
        }
    }
}
