// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tracker.Models;

#nullable disable

namespace Logictracker.Migrations
{
    [DbContext(typeof(Tracker_DevelContext))]
    [Migration("20221227175328_migrationEnvioAudit")]
    partial class migrationEnvioAudit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AI")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("META.Tracker.DTOs.ArticuloDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ArticuloCodigo")
                        .HasColumnType("bigint");

                    b.Property<string>("ArticuloDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CabeceraComprobantesAfiliado")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CantidadSolicitada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordsTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ArticuloDTO");
                });

            modelBuilder.Entity("META.Tracker.DTOs.EnvioDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CantidadGuias")
                        .HasColumnType("int");

                    b.Property<string>("Chofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChoferId")
                        .HasColumnType("int");

                    b.Property<int?>("EnvioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoMov")
                        .HasColumnType("datetime2");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordsTotal")
                        .HasColumnType("int");

                    b.Property<string>("Transportista")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("TransportistaCodigo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<string>("VehiculoTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiculoTipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnvioDTO");
                });

            modelBuilder.Entity("META.Tracker.DTOs.GuiaDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CantidadComprobantes")
                        .HasColumnType("int");

                    b.Property<int>("ClienteCodigo")
                        .HasColumnType("int");

                    b.Property<string>("ClienteDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DestinoLatitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DestinoLongitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EnvioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordsTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GuiaDTO");
                });

            modelBuilder.Entity("META.Tracker.Models.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApellidoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("META.Tracker.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChoferId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoMov")
                        .HasColumnType("datetime2");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransportistaCodigo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUltimoMovId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoferId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioUltimoMovId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("META.Tracker.Models.EnvioGuia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("EnviosGuias");
                });

            modelBuilder.Entity("META.Tracker.Models.Menue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AccesoDirecto")
                        .HasColumnType("bit");

                    b.Property<string>("AspAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspController")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuPadreId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menues");
                });

            modelBuilder.Entity("META.Tracker.Models.MenuesRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("MenuesRoles");
                });

            modelBuilder.Entity("META.Tracker.Models.Parametrico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ParametricosHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParametricosHeaderId");

                    b.ToTable("Parametricos");
                });

            modelBuilder.Entity("META.Tracker.Models.ParametricosHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParametricosHeader");
                });

            modelBuilder.Entity("META.Tracker.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaUltimoIngreso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlgAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("META.Tracker.Models.UsuariosRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("META.Tracker.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("META.Tracker.Models.vwTransportista", b =>
                {
                    b.Property<decimal>("Codigo")
                        .HasColumnType("numeric(5,0)")
                        .HasColumnName("CODIGO");

                    b.Property<long>("Idprovlogi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IDPROVLOGI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Idprovlogi"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NOMBRE");

                    b.ToView("vwTransportistas");
                });

            modelBuilder.Entity("Tracker.Models.EnvioAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Envio")
                        .HasColumnType("bigint");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long>("Guia")
                        .HasColumnType("bigint");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("EnviosAudit");
                });

            modelBuilder.Entity("META.Tracker.Models.Chofer", b =>
                {
                    b.HasOne("META.Tracker.Models.Parametrico", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("META.Tracker.Models.Envio", b =>
                {
                    b.HasOne("META.Tracker.Models.Chofer", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId");

                    b.HasOne("META.Tracker.Models.Parametrico", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("META.Tracker.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("META.Tracker.Models.Usuario", "UsuarioUltimoMov")
                        .WithMany()
                        .HasForeignKey("UsuarioUltimoMovId");

                    b.HasOne("META.Tracker.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Chofer");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioUltimoMov");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("META.Tracker.Models.EnvioGuia", b =>
                {
                    b.HasOne("META.Tracker.Models.Envio", "Envio")
                        .WithMany("Guias")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("META.Tracker.Models.Parametrico", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.Navigation("Envio");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("META.Tracker.Models.MenuesRole", b =>
                {
                    b.HasOne("META.Tracker.Models.Menue", "Menu")
                        .WithMany("MenuesRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("META.Tracker.Models.Parametrico", "Rol")
                        .WithMany("MenuesRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("META.Tracker.Models.Parametrico", b =>
                {
                    b.HasOne("META.Tracker.Models.ParametricosHeader", "ParametricosHeader")
                        .WithMany("Parametricos")
                        .HasForeignKey("ParametricosHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametricosHeader");
                });

            modelBuilder.Entity("META.Tracker.Models.UsuariosRole", b =>
                {
                    b.HasOne("META.Tracker.Models.Parametrico", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("META.Tracker.Models.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("META.Tracker.Models.Vehiculo", b =>
                {
                    b.HasOne("META.Tracker.Models.Parametrico", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("META.Tracker.Models.Parametrico", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");

                    b.Navigation("Estado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Tracker.Models.EnvioAudit", b =>
                {
                    b.HasOne("META.Tracker.Models.Parametrico", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("META.Tracker.Models.Envio", b =>
                {
                    b.Navigation("Guias");
                });

            modelBuilder.Entity("META.Tracker.Models.Menue", b =>
                {
                    b.Navigation("MenuesRoles");
                });

            modelBuilder.Entity("META.Tracker.Models.Parametrico", b =>
                {
                    b.Navigation("MenuesRoles");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("META.Tracker.Models.ParametricosHeader", b =>
                {
                    b.Navigation("Parametricos");
                });

            modelBuilder.Entity("META.Tracker.Models.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
